services:
  backend:
    image: '${DOCKER_SCOPE}/docker-project-backend'
    restart: 'always'
    networks:
      - 'appnetwork'
    ports:
      - '8081:8081'
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:8081/health"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  frontend:
    image: '${DOCKER_SCOPE}/docker-project-frontend'
    restart: 'always'
    networks:
      - 'appnetwork'
    environment:
      VUE_APP_API_URL: '${BACKEND_URL}'
    ports:
      - '8080:8080'
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:8080"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

networks:
  appnetwork:
    driver: 'bridge'
    internal: true
